export type RouteOption = {
  label: "Cheapest Route" | "Fastest Route" | "Balanced Route";
  fare: string;
  time: string;
  comfort: string;
  walkingDistance: string;
  transportType: string;
  highlight: string;
};

export type NearbyLandmark = {
  name: string;
  walkTime: string;
  clue: string;
  transportHint: string;
  phrase: string;
  exitPoint: string;
};

export type RouteRecord = {
  id: string;
  from: string;
  to: string;
  destination: string;
  aliases: string[];
  boardingPoint: string;
  alightingPoint: string;
  vehicleType: string;
  fareRange: string;
  estimatedTime: string;
  uberEstimate: string;
  savings: string;
  driverPhrase: string;
  safetyNote: string;
  confidence: "High" | "Medium";
  lastVerified: string;
  usersConfirmed: number;
  routeTone: string;
  steps: string[];
  options: {
    cheapest: RouteOption;
    fastest: RouteOption;
    balanced: RouteOption;
  };
  nearbyLandmarks: NearbyLandmark[];
};

export const routes: RouteRecord[] = [
  {
    id: "tech-junction",
    from: "KNUST Campus",
    to: "Tech Junction",
    destination: "Tech Junction",
    aliases: ["tech junction", "tech", "tech junction station"],
    boardingPoint: "Conti Bus Stop",
    alightingPoint: "Tech Junction Main Station",
    vehicleType: "Kejetia Trotro",
    fareRange: "GH₵4.50 - GH₵6.00",
    estimatedTime: "20 - 26 min",
    uberEstimate: "GH₵26 - GH₵34",
    savings: "Save about GH₵24",
    driverPhrase: "Tech Junction, main station side.",
    safetyNote: "Avoid boarding isolated late-night cars; use the main trotro queue after dark.",
    confidence: "High",
    lastVerified: "May 2026",
    usersConfirmed: 31,
    routeTone: "Great for hostel runs, gadgets, and roadside food after lectures.",
    steps: [
      "Head to Conti Bus Stop and queue for Kejetia-bound trotro.",
      "Confirm Tech Junction main station with the mate before paying.",
      "Stay on until the busy Tech Junction station area.",
      "Alight at the main station and use the zebra crossing.",
      "Walk 1 minute to nearby shops or hostels.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵4.50",
        time: "26 min",
        comfort: "Crowded peak ride",
        walkingDistance: "5 min walk",
        transportType: "Kejetia Trotro",
        highlight: "Best during daytime when queue movement is steady.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵6.00",
        time: "20 min",
        comfort: "Semi-direct",
        walkingDistance: "2 min walk",
        transportType: "Direct Taxi",
        highlight: "Cuts queue time when traffic is still light.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵5.00",
        time: "22 min",
        comfort: "Moderate",
        walkingDistance: "3 min walk",
        transportType: "Kejetia Trotro",
        highlight: "Most reliable mix for everyday commuter flow.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Conti Bus Stop",
        walkTime: "2 min",
        clue: "Yellow curb paint and campus shuttle sign",
        transportHint: "Board a Kejetia-bound trotro and mention Tech Junction.",
        phrase: "Mate, Tech Junction main station side.",
        exitPoint: "Tech Junction Main Station",
      },
      {
        name: "Unity Hall Junction",
        walkTime: "4 min",
        clue: "Orange food kiosks near the hall entrance",
        transportHint: "Pick any car loading for town through Tech.",
        phrase: "Tech Junction, please.",
        exitPoint: "Tech Junction traffic light",
      },
      {
        name: "Kotei Road Split",
        walkTime: "5 min",
        clue: "Forked road with a pharmacy billboard",
        transportHint: "Use shared taxis that join the Tech road early.",
        phrase: "Tech Junction make I drop there.",
        exitPoint: "Station frontage",
      },
    ],
  },
  {
    id: "ayeduase",
    from: "KNUST Campus",
    to: "Ayeduase",
    destination: "Ayeduase",
    aliases: ["ayeduase", "ayeduase junction", "ayeduase market"],
    boardingPoint: "Engineering Gate",
    alightingPoint: "Ayeduase Junction",
    vehicleType: "Ayeduase Taxi",
    fareRange: "GH₵3.00 - GH₵4.50",
    estimatedTime: "10 - 15 min",
    uberEstimate: "GH₵18 - GH₵24",
    savings: "Save about GH₵16",
    driverPhrase: "Ayeduase junction, please.",
    safetyNote: "Use the lit side of the junction and avoid alighting too far from the main stores.",
    confidence: "High",
    lastVerified: "May 2026",
    usersConfirmed: 42,
    routeTone: "Simple everyday route for food, hostels, pharmacies, and quick errands.",
    steps: [
      "Walk to Engineering Gate roadside queue.",
      "Board an Ayeduase taxi and mention the junction.",
      "Pay after the vehicle moves or when the mate asks.",
      "Alight at Ayeduase Junction near the roadside shops.",
      "Walk into the market lane or hostel road as needed.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵3.00",
        time: "15 min",
        comfort: "Shared ride",
        walkingDistance: "4 min walk",
        transportType: "Ayeduase Taxi",
        highlight: "Best daytime commuter option with little walking.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵4.50",
        time: "10 min",
        comfort: "Direct",
        walkingDistance: "2 min walk",
        transportType: "Direct Taxi",
        highlight: "Great for quick errands before lectures resume.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵3.50",
        time: "12 min",
        comfort: "Moderate",
        walkingDistance: "3 min walk",
        transportType: "Ayeduase Taxi",
        highlight: "Most consistent campus-to-junction flow.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Engineering Gate",
        walkTime: "3 min",
        clue: "Security booth and bridge shadow",
        transportHint: "Take any taxi calling Ayeduase.",
        phrase: "Ayeduase junction, please.",
        exitPoint: "Ayeduase Junction",
      },
      {
        name: "Commercial Area Shell",
        walkTime: "5 min",
        clue: "Bright station lights and ATM",
        transportHint: "Cars line up by the station edge heading Ayeduase.",
        phrase: "Ayeduase side make I drop there.",
        exitPoint: "Market bend",
      },
      {
        name: "University Hall Gate",
        walkTime: "6 min",
        clue: "Broad gate with football field view",
        transportHint: "Use passing Ayeduase taxis during busy hours.",
        phrase: "Ayeduase junction, boss.",
        exitPoint: "Ayeduase Junction",
      },
    ],
  },
  {
    id: "kejetia",
    from: "KNUST Campus",
    to: "Kejetia",
    destination: "Kejetia",
    aliases: ["kejetia", "kejetia market", "kumasi central"],
    boardingPoint: "Conti Bus Stop",
    alightingPoint: "Kejetia Terminal",
    vehicleType: "Kejetia Trotro",
    fareRange: "GH₵5.50 - GH₵7.00",
    estimatedTime: "28 - 36 min",
    uberEstimate: "GH₵35 - GH₵48",
    savings: "Save about GH₵34",
    driverPhrase: "Mate, Kejetia. I will alight at Roman Hill if traffic is heavy.",
    safetyNote: "Keep your bag forward in crowded queues and use the terminal exits with more foot traffic.",
    confidence: "High",
    lastVerified: "May 2026",
    usersConfirmed: 45,
    routeTone: "Best city link for shopping, terminals, and central Kumasi connections.",
    steps: [
      "Board a Kejetia trotro at Conti Bus Stop.",
      "Mention Kejetia or Roman Hill depending on traffic updates.",
      "Stay on the main route into town.",
      "Alight at Kejetia Terminal or Roman Hill if advised.",
      "Walk through the main commercial lane to your destination.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵5.50",
        time: "36 min",
        comfort: "Busy queue",
        walkingDistance: "7 min walk",
        transportType: "Kejetia Trotro",
        highlight: "Most economical for city runs with flexible timing.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵7.00",
        time: "28 min",
        comfort: "Semi-direct",
        walkingDistance: "3 min walk",
        transportType: "Express Trotro",
        highlight: "Fewer stops and better when leaving very early.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵6.00",
        time: "31 min",
        comfort: "Moderate",
        walkingDistance: "5 min walk",
        transportType: "Kejetia Trotro",
        highlight: "Reliable for most daytime market trips.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Conti Bus Stop",
        walkTime: "2 min",
        clue: "Campus shuttle sign and long queue rail",
        transportHint: "Take a Kejetia trotro from the main lane.",
        phrase: "Mate, Kejetia.",
        exitPoint: "Kejetia Terminal",
      },
      {
        name: "Republic Hall Junction",
        walkTime: "6 min",
        clue: "Hall sign and food vendors",
        transportHint: "Join town-bound vehicles heading Kejetia.",
        phrase: "Kejetia or Roman Hill, please.",
        exitPoint: "Roman Hill",
      },
      {
        name: "Tech Junction Bypass",
        walkTime: "8 min",
        clue: "Busy traffic lights and roadside minibus row",
        transportHint: "Catch passing central-bound transport if campus queues are long.",
        phrase: "Kejetia straight.",
        exitPoint: "Kejetia Terminal",
      },
    ],
  },
  {
    id: "adum",
    from: "KNUST Campus",
    to: "Adum",
    destination: "Adum",
    aliases: ["adum", "adum pz", "adum market"],
    boardingPoint: "Conti Bus Stop",
    alightingPoint: "Adum PZ",
    vehicleType: "Adum Trotro",
    fareRange: "GH₵6.50 - GH₵8.00",
    estimatedTime: "32 - 40 min",
    uberEstimate: "GH₵38 - GH₵52",
    savings: "Save about GH₵37",
    driverPhrase: "Adum PZ, please.",
    safetyNote: "Use the more populated PZ side when meeting someone or opening your phone for directions.",
    confidence: "Medium",
    lastVerified: "May 2026",
    usersConfirmed: 24,
    routeTone: "For shopping, banking, and central-city errands without paying ride-hailing prices.",
    steps: [
      "Queue at Conti Bus Stop for an Adum or Kejetia car.",
      "If using a Kejetia car, switch at Roman Hill for Adum PZ.",
      "Tell the mate clearly that you want Adum PZ.",
      "Alight near the PZ junction and stay on the busy sidewalk.",
      "Walk 2 - 4 minutes to shops or banks.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵6.50",
        time: "40 min",
        comfort: "1 transfer",
        walkingDistance: "8 min walk",
        transportType: "Trotro via Roman Hill",
        highlight: "Cheaper if you do not mind one short transfer.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵8.00",
        time: "32 min",
        comfort: "Direct seat",
        walkingDistance: "3 min walk",
        transportType: "Direct Adum Trotro",
        highlight: "Best when direct loading is available at the main queue.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵7.00",
        time: "35 min",
        comfort: "Moderate",
        walkingDistance: "5 min walk",
        transportType: "Adum Trotro",
        highlight: "Consistent route when you want less switching and fair cost.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Conti Bus Stop",
        walkTime: "2 min",
        clue: "Queue shelter and bus sign",
        transportHint: "Wait for direct Adum cars or take Kejetia and switch at Roman Hill.",
        phrase: "Adum PZ, please.",
        exitPoint: "Adum PZ",
      },
      {
        name: "Roman Hill",
        walkTime: "5 min after switch",
        clue: "Steep roadside and major transfer point",
        transportHint: "Change here if direct Adum loading is not available.",
        phrase: "Adum PZ, make I drop there.",
        exitPoint: "Adum PZ",
      },
      {
        name: "Kejetia Terminal",
        walkTime: "6 min after city entry",
        clue: "Large terminal canopy and bus bays",
        transportHint: "Pick a quick inner-city ride to PZ.",
        phrase: "PZ side, please.",
        exitPoint: "Adum PZ",
      },
    ],
  },
  {
    id: "republic-hall",
    from: "KNUST Campus",
    to: "Republic Hall",
    destination: "Republic Hall",
    aliases: ["republic hall", "republic", "rep hall"],
    boardingPoint: "Commercial Area",
    alightingPoint: "Republic Hall Junction",
    vehicleType: "Campus Shuttle / Taxi",
    fareRange: "GH₵2.50 - GH₵4.00",
    estimatedTime: "8 - 12 min",
    uberEstimate: "GH₵15 - GH₵20",
    savings: "Save about GH₵13",
    driverPhrase: "Republic Hall junction, please.",
    safetyNote: "Use the main hall junction stop and avoid the darker side road after late events.",
    confidence: "High",
    lastVerified: "May 2026",
    usersConfirmed: 29,
    routeTone: "Short campus hop for residence, meetings, and event nights.",
    steps: [
      "Walk to Commercial Area loading point.",
      "Take a campus shuttle or shared taxi heading Republic side.",
      "Mention Republic Hall junction early.",
      "Alight at the hall junction sign.",
      "Walk into the hall road or nearby bus stop.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵2.50",
        time: "12 min",
        comfort: "Shuttle",
        walkingDistance: "5 min walk",
        transportType: "Campus Shuttle",
        highlight: "Budget-friendly for daytime campus movement.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵4.00",
        time: "8 min",
        comfort: "Direct",
        walkingDistance: "2 min walk",
        transportType: "Shared Taxi",
        highlight: "Ideal after events or when carrying items.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵3.00",
        time: "10 min",
        comfort: "Moderate",
        walkingDistance: "3 min walk",
        transportType: "Campus Shuttle",
        highlight: "Easy, predictable hall connection with low cost.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Commercial Area Shell",
        walkTime: "2 min",
        clue: "ATM and fuel station glow",
        transportHint: "Board campus shuttles or shared taxis from the edge of the area.",
        phrase: "Republic Hall junction, please.",
        exitPoint: "Republic Hall Junction",
      },
      {
        name: "Unity Hall Front",
        walkTime: "4 min",
        clue: "Orange kiosks and wide sidewalk",
        transportHint: "Catch a passing vehicle heading Republic side.",
        phrase: "Republic Hall side.",
        exitPoint: "Hall junction",
      },
      {
        name: "Library Roundabout",
        walkTime: "5 min",
        clue: "Roundabout with student foot traffic",
        transportHint: "Use nearby campus taxis if shuttle queue is long.",
        phrase: "Republic Hall junction, boss.",
        exitPoint: "Hall sign",
      },
    ],
  },
  {
    id: "asafo",
    from: "KNUST Campus",
    to: "Asafo",
    destination: "Asafo",
    aliases: ["asafo", "asafo market", "asafo station", "asafo interchange"],
    boardingPoint: "Conti Bus Stop",
    alightingPoint: "Asafo Station",
    vehicleType: "Asafo Trotro",
    fareRange: "GH₵4.50 - GH₵6.00",
    estimatedTime: "18 - 25 min",
    uberEstimate: "GH₵24 - GH₵34",
    savings: "Save about GH₵22",
    driverPhrase: "Asafo station, please.",
    safetyNote: "Keep bags close at Asafo — it is a busy interchange with multiple loading lanes and heavy foot traffic.",
    confidence: "High",
    lastVerified: "May 2026",
    usersConfirmed: 38,
    routeTone: "Key transfer hub for connecting to Santasi, Airport side, and south Kumasi destinations.",
    steps: [
      "Head to Conti Bus Stop and join the trotro queue.",
      "Board a trotro heading toward Asafo or Kejetia — tell the mate Asafo station.",
      "Stay on past Tech Junction as the vehicle heads west.",
      "Alight at Asafo Station when the large interchange comes into view.",
      "Use the right-side lanes for connecting transport to further destinations.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵4.50",
        time: "25 min",
        comfort: "Shared trotro",
        walkingDistance: "4 min walk",
        transportType: "Asafo Trotro",
        highlight: "Most economical campus-to-interchange option.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵6.00",
        time: "18 min",
        comfort: "Direct",
        walkingDistance: "2 min walk",
        transportType: "Direct Taxi",
        highlight: "Cuts wait time when queue flow is slow.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵5.00",
        time: "21 min",
        comfort: "Moderate",
        walkingDistance: "3 min walk",
        transportType: "Asafo Trotro",
        highlight: "Consistent mid-range option for everyday use.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Conti Bus Stop",
        walkTime: "2 min",
        clue: "Yellow curb paint and campus shuttle sign",
        transportHint: "Board a trotro toward town and mention Asafo Station.",
        phrase: "Asafo station, please.",
        exitPoint: "Asafo Station",
      },
      {
        name: "Tech Junction Main Station",
        walkTime: "8 min",
        clue: "Busy traffic-light area — pass through heading west for Asafo",
        transportHint: "If already at Tech Junction, board any westbound car toward Asafo.",
        phrase: "Asafo please, station side.",
        exitPoint: "Asafo Station",
      },
      {
        name: "Unity Hall Junction",
        walkTime: "4 min",
        clue: "Orange food kiosks near the hall entrance",
        transportHint: "Pick any car heading into town via the Asafo road.",
        phrase: "Asafo station, boss.",
        exitPoint: "Asafo Station",
      },
    ],
  },
  {
    id: "ayigya",
    from: "KNUST Campus",
    to: "Ayigya",
    destination: "Ayigya",
    aliases: ["ayigya", "ayigya zongo", "ayigya junction"],
    boardingPoint: "KNUST Main Gate",
    alightingPoint: "Ayigya Junction",
    vehicleType: "Ayigya Shared Taxi",
    fareRange: "GH₵2.50 - GH₵4.00",
    estimatedTime: "8 - 14 min",
    uberEstimate: "GH₵16 - GH₵22",
    savings: "Save about GH₵14",
    driverPhrase: "Ayigya junction, please.",
    safetyNote: "Use the main junction point and avoid poorly lit side paths at night.",
    confidence: "High",
    lastVerified: "May 2026",
    usersConfirmed: 44,
    routeTone: "Quick, affordable hop for students with hostels or friends in Ayigya.",
    steps: [
      "Walk to KNUST Main Gate or the roadside near the gate.",
      "Board a shared taxi heading toward Ayigya or Oforikrom side.",
      "Tell the driver Ayigya junction early so they do not pass.",
      "Alight at Ayigya Junction near the main kiosks.",
      "Walk a short distance to your hostel, shop, or residence.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵2.50",
        time: "14 min",
        comfort: "Shared ride",
        walkingDistance: "4 min walk",
        transportType: "Ayigya Shared Taxi",
        highlight: "Cheapest campus-to-Ayigya option with short walk.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵4.00",
        time: "8 min",
        comfort: "Direct",
        walkingDistance: "1 min walk",
        transportType: "Direct Taxi",
        highlight: "Best when the gate has low queue and you need speed.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵3.00",
        time: "11 min",
        comfort: "Moderate",
        walkingDistance: "2 min walk",
        transportType: "Ayigya Shared Taxi",
        highlight: "Reliable everyday option with fair cost.",
      },
    },
    nearbyLandmarks: [
      {
        name: "KNUST Main Gate",
        walkTime: "2 min",
        clue: "Main campus gate with security post",
        transportHint: "Pick shared taxis heading the Ayigya or Oforikrom direction.",
        phrase: "Ayigya junction, please.",
        exitPoint: "Ayigya Junction",
      },
      {
        name: "Commercial Area Shell",
        walkTime: "5 min",
        clue: "ATM and fuel station glow",
        transportHint: "Some cars from Commercial Area also pass through Ayigya.",
        phrase: "Ayigya junction, boss.",
        exitPoint: "Ayigya Junction",
      },
      {
        name: "Republic Hall Junction",
        walkTime: "6 min",
        clue: "Hall sign with students milling around",
        transportHint: "Catch passing taxis toward Ayigya from the junction road.",
        phrase: "Ayigya please.",
        exitPoint: "Ayigya Junction",
      },
    ],
  },
  {
    id: "kotei",
    from: "KNUST Campus",
    to: "Kotei",
    destination: "Kotei",
    aliases: ["kotei", "kotei junction", "kotei new site"],
    boardingPoint: "Ayeduase Gate",
    alightingPoint: "Kotei Junction",
    vehicleType: "Kotei Shared Taxi",
    fareRange: "GH₵3.00 - GH₵4.50",
    estimatedTime: "12 - 18 min",
    uberEstimate: "GH₵18 - GH₵26",
    savings: "Save about GH₵16",
    driverPhrase: "Kotei junction, please.",
    safetyNote: "Stay on the well-lit side of the junction at night and keep your bag in front.",
    confidence: "High",
    lastVerified: "May 2026",
    usersConfirmed: 36,
    routeTone: "Popular student route for off-campus hostels, cheaper food spots, and Kotei market.",
    steps: [
      "Walk to Ayeduase Gate or Engineering Gate roadside.",
      "Board a taxi heading toward Ayeduase then Kotei direction.",
      "Pass through Ayeduase Junction and continue south toward Kotei.",
      "Alight at Kotei Junction near the main roadside kiosks.",
      "Walk into the market or hostel area as needed.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵3.00",
        time: "18 min",
        comfort: "Shared ride",
        walkingDistance: "5 min walk",
        transportType: "Kotei Shared Taxi",
        highlight: "Budget option for the extended Ayeduase-Kotei corridor.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵4.50",
        time: "12 min",
        comfort: "Direct",
        walkingDistance: "2 min walk",
        transportType: "Direct Taxi",
        highlight: "Fewer stops when traffic south of Ayeduase is light.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵3.50",
        time: "15 min",
        comfort: "Moderate",
        walkingDistance: "3 min walk",
        transportType: "Kotei Shared Taxi",
        highlight: "Most consistent flow for Kotei errands.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Ayeduase Gate",
        walkTime: "3 min",
        clue: "Campus exit toward Ayeduase and Kotei side",
        transportHint: "Take any taxi calling Ayeduase or Kotei direction.",
        phrase: "Kotei junction, please.",
        exitPoint: "Kotei Junction",
      },
      {
        name: "Engineering Gate",
        walkTime: "4 min",
        clue: "Security booth and bridge shadow",
        transportHint: "Board southbound taxis that pass through Ayeduase en route to Kotei.",
        phrase: "Kotei please, past Ayeduase.",
        exitPoint: "Kotei Junction",
      },
      {
        name: "Ayeduase Junction",
        walkTime: "10 min after boarding",
        clue: "Roadside shops and market bend at the junction",
        transportHint: "You are halfway — stay on for Kotei or board a Kotei-bound car here.",
        phrase: "Kotei junction, boss.",
        exitPoint: "Kotei Junction",
      },
    ],
  },
  {
    id: "bantama",
    from: "KNUST Campus",
    to: "Bantama",
    destination: "Bantama",
    aliases: ["bantama", "bantama high street", "bantama market"],
    boardingPoint: "Conti Bus Stop",
    alightingPoint: "Bantama Market",
    vehicleType: "Bantama Trotro",
    fareRange: "GH₵6.00 - GH₵7.50",
    estimatedTime: "28 - 38 min",
    uberEstimate: "GH₵34 - GH₵48",
    savings: "Save about GH₵32",
    driverPhrase: "Bantama market, please.",
    safetyNote: "Bantama is busy — keep your bag forward and stay close to the kiosk side when alighting.",
    confidence: "High",
    lastVerified: "May 2026",
    usersConfirmed: 27,
    routeTone: "Access to Bantama's market, high street shops, and northward Kumasi connections.",
    steps: [
      "Board a trotro at Conti Bus Stop heading toward the city.",
      "Tell the mate Bantama market.",
      "Pass through or near Roman Hill and continue toward Bantama.",
      "Alight at Bantama Market junction.",
      "Walk into the market lane or connect to northward destinations.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵6.00",
        time: "38 min",
        comfort: "Shared trotro",
        walkingDistance: "6 min walk",
        transportType: "Bantama Trotro",
        highlight: "Best value for the campus-to-Bantama stretch.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵7.50",
        time: "28 min",
        comfort: "Fewer stops",
        walkingDistance: "2 min walk",
        transportType: "Express Trotro",
        highlight: "Ideal when leaving before peak hour traffic builds.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵6.50",
        time: "32 min",
        comfort: "Moderate",
        walkingDistance: "4 min walk",
        transportType: "Bantama Trotro",
        highlight: "Reliable daytime connection to Bantama.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Conti Bus Stop",
        walkTime: "2 min",
        clue: "Campus shuttle sign and long queue rail",
        transportHint: "Board a trotro heading toward Bantama via the city route.",
        phrase: "Bantama market, please.",
        exitPoint: "Bantama Market",
      },
      {
        name: "Roman Hill",
        walkTime: "20 min after boarding",
        clue: "Steep roadside section — a landmark you will pass mid-journey",
        transportHint: "Stay on past Roman Hill and continue to Bantama.",
        phrase: "Bantama please, I will not drop at Roman Hill.",
        exitPoint: "Bantama Market",
      },
      {
        name: "Unity Hall Junction",
        walkTime: "4 min",
        clue: "Orange food kiosks near the hall entrance",
        transportHint: "Pick any car heading toward the city that goes through Bantama.",
        phrase: "Bantama market, boss.",
        exitPoint: "Bantama Market",
      },
    ],
  },
  {
    id: "suame",
    from: "KNUST Campus",
    to: "Suame",
    destination: "Suame",
    aliases: ["suame", "suame magazine", "suame roundabout"],
    boardingPoint: "Conti Bus Stop",
    alightingPoint: "Suame Magazine",
    vehicleType: "Suame Trotro",
    fareRange: "GH₵6.50 - GH₵8.50",
    estimatedTime: "32 - 44 min",
    uberEstimate: "GH₵38 - GH₵55",
    savings: "Save about GH₵36",
    driverPhrase: "Suame magazine, please.",
    safetyNote: "Suame is an auto-industry hub — watch for slow-moving vehicles and workshop traffic when alighting.",
    confidence: "Medium",
    lastVerified: "May 2026",
    usersConfirmed: 19,
    routeTone: "For spare parts, mechanical work, and northward Kumasi destinations beyond Bantama.",
    steps: [
      "Board a trotro at Conti Bus Stop heading toward Kejetia.",
      "Tell the mate Suame magazine — confirm you want Suame not Bantama.",
      "Continue north past Bantama area.",
      "Alight at Suame Magazine or the junction on the main road.",
      "Walk into the workshop area or connect to further destinations.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵6.50",
        time: "44 min",
        comfort: "Multiple stops",
        walkingDistance: "5 min walk",
        transportType: "Suame Trotro",
        highlight: "Budget route — expect stops at Bantama before continuing north.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵8.50",
        time: "32 min",
        comfort: "Fewer stops",
        walkingDistance: "2 min walk",
        transportType: "Express Trotro",
        highlight: "Best before morning rush hour when Kejetia area flows well.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵7.50",
        time: "38 min",
        comfort: "Moderate",
        walkingDistance: "4 min walk",
        transportType: "Suame Trotro",
        highlight: "Most consistent option for Suame runs.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Conti Bus Stop",
        walkTime: "2 min",
        clue: "Yellow curb paint and campus shuttle sign",
        transportHint: "Board a Kejetia trotro and tell the mate Suame magazine.",
        phrase: "Suame magazine, please.",
        exitPoint: "Suame Magazine",
      },
      {
        name: "Bantama Market",
        walkTime: "25 min after boarding",
        clue: "Busy market junction — you will pass through here",
        transportHint: "Stay on past Bantama and continue north to Suame.",
        phrase: "Suame magazine, I am not dropping at Bantama.",
        exitPoint: "Suame Magazine",
      },
      {
        name: "Tech Junction Bypass",
        walkTime: "8 min",
        clue: "Busy traffic lights and roadside minibus row",
        transportHint: "From Tech Junction you can board a northward Suame car.",
        phrase: "Suame magazine side.",
        exitPoint: "Suame Magazine",
      },
    ],
  },
  {
    id: "ahodwo",
    from: "KNUST Campus",
    to: "Ahodwo",
    destination: "Ahodwo",
    aliases: ["ahodwo", "ahodwo roundabout", "ahodwo estate"],
    boardingPoint: "Conti Bus Stop",
    alightingPoint: "Ahodwo Roundabout",
    vehicleType: "Ahodwo Trotro",
    fareRange: "GH₵5.00 - GH₵7.00",
    estimatedTime: "24 - 34 min",
    uberEstimate: "GH₵30 - GH₵44",
    savings: "Save about GH₵28",
    driverPhrase: "Ahodwo roundabout, please.",
    safetyNote: "Ahodwo roundabout is well lit — use the main pedestrian crossing and stay visible.",
    confidence: "Medium",
    lastVerified: "May 2026",
    usersConfirmed: 22,
    routeTone: "For banks, supermarkets, Ahodwo estates, and south-west Kumasi connections.",
    steps: [
      "Board a trotro at Conti Bus Stop heading toward the city.",
      "Tell the mate Ahodwo roundabout — some cars go via Roman Hill or Kejetia first.",
      "Stay on past the Roman Hill transfer point heading south-west.",
      "Alight at Ahodwo Roundabout.",
      "Walk toward your bank, supermarket, or estate road.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵5.00",
        time: "34 min",
        comfort: "Via city route",
        walkingDistance: "6 min walk",
        transportType: "Ahodwo Trotro",
        highlight: "Most affordable but involves longer city route.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵7.00",
        time: "24 min",
        comfort: "Direct",
        walkingDistance: "2 min walk",
        transportType: "Direct Taxi",
        highlight: "Cuts time significantly on lighter traffic days.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵6.00",
        time: "28 min",
        comfort: "Moderate",
        walkingDistance: "4 min walk",
        transportType: "Ahodwo Trotro",
        highlight: "Best mix of cost and reliability.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Conti Bus Stop",
        walkTime: "2 min",
        clue: "Campus shuttle sign and long queue rail",
        transportHint: "Board a trotro toward town and tell the mate Ahodwo roundabout.",
        phrase: "Ahodwo roundabout, please.",
        exitPoint: "Ahodwo Roundabout",
      },
      {
        name: "Roman Hill",
        walkTime: "18 min after boarding",
        clue: "Steep roadside — transfer or continue south-west for Ahodwo",
        transportHint: "At Roman Hill, look for cars heading Ahodwo or Santasi direction.",
        phrase: "Ahodwo roundabout, boss.",
        exitPoint: "Ahodwo Roundabout",
      },
      {
        name: "Kejetia Terminal",
        walkTime: "25 min after boarding",
        clue: "Large terminal canopy and bus bays",
        transportHint: "From Kejetia, pick a short Ahodwo-bound car on the south-west side.",
        phrase: "Ahodwo roundabout, please.",
        exitPoint: "Ahodwo Roundabout",
      },
    ],
  },
  {
    id: "airport",
    from: "KNUST Campus",
    to: "Airport",
    destination: "Airport",
    aliases: ["airport", "airport roundabout", "kumasi airport", "kaase", "airport area"],
    boardingPoint: "Conti Bus Stop",
    alightingPoint: "Airport Roundabout",
    vehicleType: "Airport Trotro",
    fareRange: "GH₵5.50 - GH₵7.50",
    estimatedTime: "28 - 38 min",
    uberEstimate: "GH₵32 - GH₵48",
    savings: "Save about GH₵30",
    driverPhrase: "Airport roundabout, please.",
    safetyNote: "Airport road is wide — use the proper pedestrian crossing at the roundabout and stay alert for fast vehicles.",
    confidence: "Medium",
    lastVerified: "May 2026",
    usersConfirmed: 18,
    routeTone: "For Kumasi Airport departures, Kaase Industrial Area, and south Kumasi destinations.",
    steps: [
      "Board a trotro at Conti Bus Stop heading toward the city.",
      "Tell the mate Airport roundabout or Kaase side.",
      "The car will likely pass through Asafo Station first.",
      "Continue south from Asafo toward the Airport Roundabout.",
      "Alight at the roundabout and use the pedestrian crossing.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵5.50",
        time: "38 min",
        comfort: "Via Asafo",
        walkingDistance: "5 min walk",
        transportType: "Airport Trotro",
        highlight: "Budget option via Asafo interchange — slight detour but saves money.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵7.50",
        time: "28 min",
        comfort: "More direct",
        walkingDistance: "2 min walk",
        transportType: "Direct Taxi",
        highlight: "Best for airport departures where time matters.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵6.50",
        time: "32 min",
        comfort: "Moderate",
        walkingDistance: "3 min walk",
        transportType: "Airport Trotro",
        highlight: "Consistent route for non-urgent Airport trips.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Conti Bus Stop",
        walkTime: "2 min",
        clue: "Yellow curb paint and campus shuttle sign",
        transportHint: "Board a trotro and tell the mate Airport roundabout.",
        phrase: "Airport roundabout, please.",
        exitPoint: "Airport Roundabout",
      },
      {
        name: "Asafo Station",
        walkTime: "15 min after boarding",
        clue: "Busy interchange — pass through, continue south for Airport",
        transportHint: "At Asafo, confirm the vehicle is heading Airport or Kaase side.",
        phrase: "Airport roundabout, please — past Asafo.",
        exitPoint: "Airport Roundabout",
      },
      {
        name: "Tech Junction Main Station",
        walkTime: "8 min",
        clue: "Busy traffic-light area",
        transportHint: "From Tech Junction, board Airport or Kaase-bound transport.",
        phrase: "Airport roundabout, boss.",
        exitPoint: "Airport Roundabout",
      },
    ],
  },
  {
    id: "manhyia",
    from: "KNUST Campus",
    to: "Manhyia",
    destination: "Manhyia",
    aliases: ["manhyia", "manhyia palace", "manhyia roundabout"],
    boardingPoint: "Conti Bus Stop",
    alightingPoint: "Manhyia Palace",
    vehicleType: "Manhyia Trotro",
    fareRange: "GH₵6.50 - GH₵8.50",
    estimatedTime: "35 - 46 min",
    uberEstimate: "GH₵40 - GH₵58",
    savings: "Save about GH₵38",
    driverPhrase: "Manhyia Palace, please.",
    safetyNote: "Manhyia is a busy area during royal or public events — arrive early and use the main road exits.",
    confidence: "Medium",
    lastVerified: "May 2026",
    usersConfirmed: 16,
    routeTone: "For the Asantehene Palace, Manhyia area institutions, and north Kumasi access.",
    steps: [
      "Board a trotro at Conti Bus Stop heading toward Kejetia.",
      "Tell the mate Manhyia Palace — confirm before paying.",
      "Continue north through or past Bantama toward Manhyia.",
      "Alight near Manhyia Palace area.",
      "Walk to the palace, nearby offices, or institutions.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵6.50",
        time: "46 min",
        comfort: "Multiple stops",
        walkingDistance: "6 min walk",
        transportType: "Manhyia Trotro",
        highlight: "Budget route via city — expect a longer journey.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵8.50",
        time: "35 min",
        comfort: "Fewer stops",
        walkingDistance: "2 min walk",
        transportType: "Express Trotro",
        highlight: "Best early morning before city congestion builds.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵7.50",
        time: "40 min",
        comfort: "Moderate",
        walkingDistance: "4 min walk",
        transportType: "Manhyia Trotro",
        highlight: "Reliable for most daytime Manhyia trips.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Conti Bus Stop",
        walkTime: "2 min",
        clue: "Campus shuttle sign and long queue rail",
        transportHint: "Board a Kejetia trotro and mention Manhyia Palace to the mate.",
        phrase: "Manhyia Palace, please.",
        exitPoint: "Manhyia Palace",
      },
      {
        name: "Bantama Market",
        walkTime: "28 min after boarding",
        clue: "Busy market junction — continue north past it for Manhyia",
        transportHint: "Stay on past Bantama and ask the mate to drop you at Manhyia.",
        phrase: "Manhyia — not Bantama.",
        exitPoint: "Manhyia Palace",
      },
      {
        name: "Tech Junction Bypass",
        walkTime: "8 min",
        clue: "Busy traffic lights and roadside minibus row",
        transportHint: "From Tech Junction, you can connect to Manhyia-bound transport.",
        phrase: "Manhyia Palace, boss.",
        exitPoint: "Manhyia Palace",
      },
    ],
  },
  {
    id: "santasi",
    from: "KNUST Campus",
    to: "Santasi",
    destination: "Santasi",
    aliases: ["santasi", "santasi roundabout", "santasi junction"],
    boardingPoint: "Conti Bus Stop",
    alightingPoint: "Santasi Roundabout",
    vehicleType: "Santasi Trotro",
    fareRange: "GH₵6.00 - GH₵8.00",
    estimatedTime: "32 - 42 min",
    uberEstimate: "GH₵36 - GH₵52",
    savings: "Save about GH₵34",
    driverPhrase: "Santasi roundabout, please.",
    safetyNote: "Santasi roundabout has fast-moving vehicles — alight close to the loading point and cross carefully.",
    confidence: "Medium",
    lastVerified: "May 2026",
    usersConfirmed: 15,
    routeTone: "For south-west Kumasi residential areas, schools, and Santasi market connections.",
    steps: [
      "Board a trotro at Conti Bus Stop heading toward the city.",
      "Tell the mate Santasi roundabout.",
      "The route passes through Roman Hill and Ahodwo direction.",
      "Continue south past Ahodwo Roundabout toward Santasi.",
      "Alight at Santasi Roundabout near the roadside market.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵6.00",
        time: "42 min",
        comfort: "Via city",
        walkingDistance: "6 min walk",
        transportType: "Santasi Trotro",
        highlight: "Cheapest option — route passes through Ahodwo so expect stops.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵8.00",
        time: "32 min",
        comfort: "More direct",
        walkingDistance: "2 min walk",
        transportType: "Direct Taxi",
        highlight: "Best when you need to reach south Kumasi without delays.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵7.00",
        time: "36 min",
        comfort: "Moderate",
        walkingDistance: "4 min walk",
        transportType: "Santasi Trotro",
        highlight: "Most consistent option for Santasi area journeys.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Conti Bus Stop",
        walkTime: "2 min",
        clue: "Campus shuttle sign and long queue rail",
        transportHint: "Board a trotro toward town and mention Santasi roundabout.",
        phrase: "Santasi roundabout, please.",
        exitPoint: "Santasi Roundabout",
      },
      {
        name: "Ahodwo Roundabout",
        walkTime: "22 min after boarding",
        clue: "Roundabout with shops — continue south for Santasi",
        transportHint: "At Ahodwo, board a Santasi-bound car if your current one stops here.",
        phrase: "Santasi please, past Ahodwo.",
        exitPoint: "Santasi Roundabout",
      },
      {
        name: "Roman Hill",
        walkTime: "18 min after boarding",
        clue: "Steep roadside landmark — transfer point",
        transportHint: "Continue past Roman Hill heading south-west for Santasi.",
        phrase: "Santasi roundabout, boss.",
        exitPoint: "Santasi Roundabout",
      },
    ],
  },
  {
    id: "anloga",
    from: "KNUST Campus",
    to: "Anloga Junction",
    destination: "Anloga Junction",
    aliases: ["anloga", "anloga junction", "anloga market"],
    boardingPoint: "Conti Bus Stop",
    alightingPoint: "Anloga Junction",
    vehicleType: "Anloga Trotro / Taxi",
    fareRange: "GH₵3.50 - GH₵5.00",
    estimatedTime: "14 - 20 min",
    uberEstimate: "GH₵18 - GH₵26",
    savings: "Save about GH₵17",
    driverPhrase: "Anloga junction, please.",
    safetyNote: "Anloga junction is a busy mid-point — use the main roadside and watch for trotros pulling in quickly.",
    confidence: "High",
    lastVerified: "May 2026",
    usersConfirmed: 33,
    routeTone: "A mid-route junction for connecting to Asafo, Kejetia, and south-west destinations.",
    steps: [
      "Head to Conti Bus Stop and join the trotro queue heading toward town.",
      "Tell the mate Anloga junction — it is a short ride before Asafo.",
      "Stay on and watch for the Anloga Junction area on the right.",
      "Alight at Anloga Junction when you see the roadside market.",
      "Connect to further destinations or walk to your stop.",
    ],
    options: {
      cheapest: {
        label: "Cheapest Route",
        fare: "GH₵3.50",
        time: "20 min",
        comfort: "Shared trotro",
        walkingDistance: "4 min walk",
        transportType: "Anloga Trotro",
        highlight: "Short, budget-friendly hop to this key junction.",
      },
      fastest: {
        label: "Fastest Route",
        fare: "GH₵5.00",
        time: "14 min",
        comfort: "Direct",
        walkingDistance: "1 min walk",
        transportType: "Shared Taxi",
        highlight: "Fastest when light traffic keeps the journey under 15 minutes.",
      },
      balanced: {
        label: "Balanced Route",
        fare: "GH₵4.00",
        time: "17 min",
        comfort: "Moderate",
        walkingDistance: "2 min walk",
        transportType: "Anloga Trotro",
        highlight: "Reliable option for everyday use.",
      },
    },
    nearbyLandmarks: [
      {
        name: "Conti Bus Stop",
        walkTime: "2 min",
        clue: "Yellow curb paint and campus shuttle sign",
        transportHint: "Board any Kejetia or Asafo-bound trotro — Anloga is an early stop.",
        phrase: "Anloga junction, please.",
        exitPoint: "Anloga Junction",
      },
      {
        name: "Unity Hall Junction",
        walkTime: "4 min",
        clue: "Orange food kiosks near the hall entrance",
        transportHint: "Pick a town-bound car from here — Anloga is a short distance.",
        phrase: "Anloga junction, boss.",
        exitPoint: "Anloga Junction",
      },
      {
        name: "Asafo Station",
        walkTime: "8 min from Anloga",
        clue: "Major interchange west of Anloga — if you overshoot, board back",
        transportHint: "If you miss Anloga, alight at Asafo and take a short return.",
        phrase: "Anloga junction, make I drop there.",
        exitPoint: "Anloga Junction",
      },
    ],
  },
];

export const driverPhraseExamples = [
  "Boss, Kejetia side.",
  "Mate, Kejetia, I will alight at Roman Hill.",
  "Ayeduase junction, please.",
  "Tech Junction, main station side.",
];

export const reportActions = [
  "Report wrong fare",
  "Suggest better route",
  "Station moved",
  "Unsafe route",
];

export function findRouteByQuery(query: string) {
  const normalized = query.trim().toLowerCase();

  if (!normalized) {
    return routes[0];
  }

  return (
    routes.find(
      (route) =>
        route.destination.toLowerCase().includes(normalized) ||
        route.aliases.some((alias) => alias.includes(normalized)),
    ) ?? routes[0]
  );
}

